default: &default
  adapter:  <%= ENV['ADAPTER'] %>
  encoding: <%= ENV['ENCODING'] %>
  database: <%= ENV['DATABASE'] %>
  host:     <%= ENV['HOST'] %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>

development:
  <<: *default
  pool: 5
  timeout: 5000

test:
  <<: *default
  pool: 5
  timeout: 5000

production:
  <<: *default
  pool: 5
  timeout: 5000
