# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de4d9f1d23bd570675ea43b23a69c7477e3903c5d70e949a7752bbb992d0e93a128fd0a3516490146b2b96a5861e07822d7805d896a4b4712801c227ddec1c3b

test:
  secret_key_base: ba373f700bba72edd8fe5deaa92f3c0b3009103499613e59c910ac660a1617dd355e7577d9f84fce215abedfae5196cf31ebfe8785648e194b8ed646e81b2d72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["secret_key_base"] %>
